### ISSUE TITLE
Review of ANS student conf paper revisions

### ISSUE THREAD

**Issue by gwenchee** [arfc/2018-chee-ansstudconf2018#1]
This Issue can be closed once @katyhuff reviews my ANS student conf paper revisions.

**Comment by gwenchee** [comment]
Question: Should i include a conclusion? I looked at the conf publications in the zotero, and some have conclusions while others do not. I have a sample conclusion written in the tex file that is commented out.

**Comment by katyhuff** [comment]
see #3

**Comment by gwenchee** [comment]
I merged all the commits.
