### ISSUE TITLE
repo meta questions

### ISSUE THREAD

**Issue by katyhuff** [arfc/2018-chee-ansstudconf2018#2]
1) Does this repository need to be private or can it be public?
2) The repo name probably doesn't need the year in it twice. Perhaps chee-stuconf-2018 is sufficient.
3) To avoid confusion, are you ok with deleting https://github.com/gwenchee/ans-studentconf2018 (which has a completely different commit history for some reason and it is therefore impossible to make commits to both.) 
4) if you do delete https://github.com/gwenchee/ans-studentconf2018, then of course you'll need to re-fork this repo.

**Comment by gwenchee** [comment]
1. I made it public 
2. I renamed it. 
3. Oh yes, my bad. I initially was working on that one, and only realized that i should have made an arfc one at the end. And so i did, but forgot to delete the one in the gwenchee repository. 
4. And yes.

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/07b628a8-24e3-48e8-8d44-cc1ab7db576f-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
