### ISSUE TITLE
Add this publication to Zotero

### ISSUE THREAD

**Issue by katyhuff** [arfc/2018-chee-ansstudconf2018#4]
Please add this publication and its metadata to the group zotero in ARFC> group-pubs > conf-pubs

**Comment by gwenchee** [comment]
done!

**Comment by katyhuff** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/b60cb965-cc0a-4365-8d1f-8d56e9255948-aef391d1-ee2a-4ffc-b1c7-1c24444a7cae-v1.png?transparent=1&palette=1&width=246)
